Pr coverage insert into  moc
matrixorigin/CI pull request #150
Opened 2024-10-12 09:55 UTC by Rosyrain

2024-10-12 10:49 UTC, Rosyrain commented
### 测试
需在在MO仓库中添加新的workflow文件
具体PR link：

补充说明
1. 使用到的Rosyrain/matrixone三条分支均来自matrixorigin/matrixone的main分支
2. PR-coverage-moc进行revert 2条commit，向PR-coverage-moc-test提交PR
3. 等待PR合并之后，PR-coverage-moc-2进行revert 1条commit记录，向PR-coverage-moc-test提交PR
<hr>
1. 第一次提交PR时：https://github.com/Rosyrain/matrixone/actions/runs/11303791900/job/31442860309
<img width="954" alt="image" src="https://github.com/user-attachments/assets/0bb6cdcb-015e-4552-9412-73ff3d4176f5">
<img width="954" alt="image" src="https://github.com/user-attachments/assets/4dba121d-f83a-47ee-b644-3f3d2ed56728">
<img width="979" alt="image" src="https://github.com/user-attachments/assets/875e257f-d4a3-401e-b63f-07fd6e2dfd26">
2. 第一次PR进行合并后：https://github.com/Rosyrain/matrixone/actions/runs/11304829352/job/31443772997
<img width="971" alt="image" src="https://github.com/user-attachments/assets/77dbfc01-8231-43fd-9edd-4a66fe1b7ed0">
<img width="977" alt="image" src="https://github.com/user-attachments/assets/bac7853a-8fb2-4483-a03e-5eb4b08edd79">
3. 第二次提交PR时：https://github.com/Rosyrain/matrixone/actions/runs/11304921619/job/31443858426

2024-10-12 11:55 UTC, guguducken requested changes

2024-10-12 11:55 UTC, guguducken commented on .github/workflows/merge-update-moc.yaml
为什么要新增这个文件呢？这个workflow要从哪里去拿覆盖率文件呢？

2024-10-12 11:55 UTC, guguducken commented on .github/workflows/utils.yaml
> +          ut_coverage_file: ${{ github.workspace }}/all_middle_files/ut_coverage_sort.out
all_middle_files这个路径是在哪里生成，哪里设置的呢？

2024-10-12 12:48 UTC, Rosyrain commented on .github/workflows/utils.yaml
> +          ut_coverage_file: ${{ github.workspace }}/all_middle_files/ut_coverage_sort.out
这个文件在- name: Download UT BVT Coverage and diff.patch Files中生成的，之前尝试使用原始的ut_coverage.out文件应该是由于文件太大一直会报无法正常读取文件的错误，所以采用了sort之后的文件。

2024-10-12 13:21 UTC, guguducken commented on .github/workflows/utils.yaml
> +          ut_coverage_file: ${{ github.workspace }}/all_middle_files/ut_coverage_sort.out
all_middle_files这个路径存在吗？是不是写错了？我在这一步里面没有找到

2024-10-15 14:47 UTC, Rosyrain commented
测试链接：内容如上
https://github.com/Rosyrain/matrixone/actions/runs/11343570861/job/31549255159
https://github.com/Rosyrain/matrixone/actions/runs/11344332042/job/31558214535
https://github.com/Rosyrain/matrixone/actions/runs/11347316225/job/31558430643
![Uploading image.png…]()

2024-11-28 06:17 UTC, guguducken approved these changes

2024-11-28 06:17 UTC, merged