fix ut panic Exit-Code
matrixorigin/CI pull request #155
Opened 2024-10-17 10:18 UTC by Rosyrain

修复ut test时因为 `| tee xxx.out`导致退出状态码为0，无法正常捕获panic
测试链接，已成功捕获panic
https://github.com/Rosyrain/matrixone/actions/runs/11382671038/job/31666674954
https://github.com/Rosyrain/matrixone/actions/runs/11382666089/job/31666680799

2024-10-17 10:30 UTC, guguducken requested changes

2024-10-17 10:30 UTC, guguducken commented on .github/workflows/robot.yaml
>          timeout-minutes: 120
这里需要对下面的step检查一下，加上always，确保在ut失败的时候也能发消息出去

2024-10-18 10:10 UTC, Rosyrain commented on .github/workflows/robot.yaml
>          timeout-minutes: 120
不影响消息发送

2024-10-19 03:43 UTC, Rosyrain commented
新加测试链接
1. https://github.com/Rosyrain/matrixone/actions/runs/11396855151/job/31711388802
2. https://github.com/Rosyrain/matrixone/actions/runs/11401110216/job/31723344952
3.  https://github.com/Rosyrain/github_action_test/actions/runs/11396505177/job/31710441604
3测试是为1测试的消息内容进行验证

2024-10-21 03:53 UTC, guguducken approved these changes

2024-10-21 03:56 UTC, merged