fix ut panic Exit-Code for 1.2-dev
matrixorigin/CI pull request #156
Opened 2024-10-17 10:22 UTC by Rosyrain

2024-10-17 10:32 UTC, guguducken requested changes

2024-10-17 10:32 UTC, guguducken commented on .github/workflows/robot.yaml
> +          set -o pipefail
这里对后续的step检查一下，确保就算这里失败，后续消息也能发出去，最好是在后续的消息里加一下bvt和ut测试的结果

2024-10-19 04:58 UTC, Rosyrain commented on .github/workflows/robot.yaml
> +          set -o pipefail
已验证

2024-10-21 03:53 UTC, guguducken approved these changes

2024-10-21 03:56 UTC, merged