issue-no-PR action
matrixorigin/CI pull request #71
Opened 2024-07-18 09:54 UTC by Rosyrain

Add github action about issue-no-PR.

2024-07-19 03:43 UTC, guguducken requested changes

2024-07-19 03:43 UTC, guguducken commented on actions/issue-no_pull_request-action/main.go
> +		labelData := `["needs-review","no-pull_request"]`
具体label也应该通过外部传递，不应该在这里写死

2024-07-19 03:43 UTC, guguducken commented on actions/issue-no_pull_request-action/pkg/http/http.go
> +	req.Header.Set("Authorization", fmt.Sprintf("token %s", token))
这里应该是Bearer吧

2024-07-19 10:29 UTC, guguducken requested changes

2024-07-19 10:29 UTC, guguducken commented on .github/workflows/robot.yaml
> +    if: github.actor != 'suki77'
判断条件不对

2024-07-19 10:29 UTC, guguducken commented on .github/workflows/robot.yaml
> +        with:
相关label设置呢？

2024-07-19 10:29 UTC, guguducken commented on .github/workflows/robot.yaml
> +          REPOSITORY: ${{ github.repository }}
github.repository这个context知道具体的内容吗？在后面用注释加个注释吧

2024-07-19 10:29 UTC, guguducken commented on .github/workflows/robot.yaml
> +          GITHUB_TOKEN: ${{ secrets.TOKEN }}
这个token看一下其他的workflow啊，这个是不存在的，不能用这个

2024-07-19 10:29 UTC, guguducken commented on .github/workflows/robot.yaml
> +        uses: Rosyrain/CI/actions/issue-no_pull_request-action@main
这个仓库不对吧？而且改一下名字吧，issue-no_pull_request-action这个也太长了

2024-07-19 10:29 UTC, guguducken commented on .github/workflows/robot.yaml
> +          ASSIGNEES: suki77
是这个名字吗。。。

2024-07-19 10:31 UTC, guguducken requested changes

2024-07-19 10:31 UTC, guguducken commented on .github/workflows/robot.yaml
> +  check_issues_noRelatedPR:
改一下名字吧，这个明明方式有点混乱

2024-07-22 03:13 UTC, guguducken requested changes

2024-07-22 03:13 UTC, guguducken commented on .github/workflows/robot.yaml
> +    if: ${{ github.event_name == 'issues' && github.event.action == 'closed' && github.actor != 'sukki77' }}
判断条件还是有问题，这样子99%的情况下不会生效

2024-07-22 03:39 UTC, Rosyrain commented on .github/workflows/robot.yaml
> +    if: ${{ github.event_name == 'issues' && github.event.action == 'closed' && github.actor != 'sukki77' }}
触发条件--issue关闭时判断是否为指定人员，若不是指定人员执行剩下操作，反之跳过
不太懂为什么大部分时候不会生效

2024-08-01 03:57 UTC, guguducken requested changes

2024-08-01 03:57 UTC, guguducken commented on .github/workflows/robot.yaml
> +      - name: Check closed issues without PR
Reopen Issue Without PR

2024-08-01 03:57 UTC, guguducken commented on .github/workflows/merge-trigger-tke.yaml
> +          mo_svc_ip=$(kubectl -n mo-checkin-regression-${{ github.event.pull_request.number }} get svc | grep "proxy" | grep "6001/TCP"|awk '{print $3}')
这个先修改回去啊

2024-08-01 03:57 UTC, guguducken commented on actions/issue-no-PR/action.yml
> +name: issue-no_pull_request-action
这个名字也改一下啊

2024-08-01 03:57 UTC, guguducken commented on actions/issue-no-PR/action.yml
> +  base_url:
这一步不需要，workflow运行时会有默认的环境变量

2024-08-01 03:57 UTC, guguducken commented on actions/issue-no-PR/main.go
> +	labelsNeedStr := strings.Trim(labelsNeed, `[]`)
这里应该去掉，在input时就不携带[]

2024-08-01 03:57 UTC, guguducken commented on actions/issue-no-PR/action.yml
> +    default: '["tech-request","feature","Feature","kind/feature","attention/feature-incomplete","bug/ut","Bug fix","kind/bug","kind/subtask","kind/tech-request"]'
这个没有必要在输入时携带[]这两个了，直接用"xxx/xxx,xxxx,xxxxx/xxx"这种格式就好了

2024-08-01 03:57 UTC, guguducken commented on actions/issue-no-PR/action.yml
> +    default: '["no-pr-linked"]'
这个没有必要在输入时携带[]这两个了，直接用"xxx/xxx,xxxx,xxxxx/xxx"这种格式就好了

2024-08-20 11:27 UTC, guguducken approved these changes

2024-08-20 11:28 UTC, merged