add mo workflow file
matrixorigin/CI pull request #8
Opened 2024-03-27 03:17 UTC by lcxznpy

2024-03-27 03:22 UTC, guguducken requested changes

2024-03-27 03:22 UTC, guguducken commented on .github/workflows/e2e-compose.yaml
> +    name: multi cn e2e bvt test docker compose(PUSH)
每个job的名称需要与现在matrixone仓库中的job名称保持一致

2024-03-27 03:22 UTC, guguducken commented on .github/workflows/e2e-compose.yaml
> +          name: multi-cn-e2e-push-docker-compose-log-pessimistic
上传文件名称也需要与现在matrixone仓库中的保持一致

2024-03-27 03:44 UTC, lcxznpy commented on .github/workflows/e2e-compose.yaml
> +          name: multi-cn-e2e-push-docker-compose-log-pessimistic
改好了

2024-03-28 02:41 UTC, guguducken approved these changes

2024-03-28 02:41 UTC, merged