rm labels
matrixorigin/CI pull request #98
Opened 2024-08-20 10:07 UTC by Rosyrain

When an `assignee` event occurs, the `needs-triage` tag will be removed if the assigned is not `matrix-meow`.

2024-08-20 10:09 UTC, Rosyrain commented
测试action：https://github.com/Rosyrain/github_action_test/actions/runs/10469484330/job/28992615702
使用到的issue：https://github.com/Rosyrain/github_action_test/issues/50
测试结果：
<img width="965" alt="image" src="https://github.com/user-attachments/assets/c11f5b73-1ed2-40de-b5c6-59e6ec17f1dd">

2024-08-20 11:23 UTC, guguducken requested changes

2024-08-20 11:23 UTC, guguducken commented on .github/workflows/robot.yaml
> +            BASE_URL: https://api.github.com
此处不要写死，直接使用workflow中的GitHub context中的内容

2024-08-20 11:23 UTC, guguducken commented on .github/workflows/robot.yaml
> +          if: ${{ steps.step1.outputs.send == 'yes' }}
这个send是啥？

2024-08-20 11:23 UTC, guguducken commented on .github/workflows/robot.yaml
> +            REPOSITORY: ${{ github.repository }}  # 获取执行该作业的仓库名 形如: matrixorigin/CI
这个和action.yaml里面定义的input保持一致吧，大小写

2024-08-20 11:23 UTC, guguducken commented on actions/rm-labels/main.go
> +	labelURL := fmt.Sprintf("%s/repos/%s/issues/%d/labels", baseURL, repo, issueNumber)
这里用删除的接口只删除那些需要删除的label是否更好？

2024-08-20 11:23 UTC, guguducken commented on actions/rm-labels/pkg/http/http.go
> +func Request(method, url, token string, data io.Reader, contentType string) (resp *http.Response, err error) {
这里数据量也不大，直接返回body内的内容？

2024-08-20 11:24 UTC, guguducken requested changes

2024-08-20 11:24 UTC, guguducken commented on .github/workflows/robot.yaml
> +      if: ${{ github.event_name == 'issues' && github.event.action == 'assigned' && github.event.assignee.login!= 'matrix-meow' }}
这个assignee的判断放到代码里面吧

2024-08-20 12:38 UTC, Rosyrain commented on .github/workflows/robot.yaml
> +          if: ${{ steps.step1.outputs.send == 'yes' }}
send是套用之前的关闭issue之后输出一个是否发送信息的判断，想着后续可能会重复使用这个action去删其他标签，可能有一些标签需要根据结果做后续处理，我就保留了

2024-08-20 12:39 UTC, Rosyrain commented on actions/rm-labels/main.go
> +	labelURL := fmt.Sprintf("%s/repos/%s/issues/%d/labels", baseURL, repo, issueNumber)
之前没发现有 删除一个标签 的接口，会做相应更改

2024-08-20 13:26 UTC, guguducken commented on .github/workflows/robot.yaml
> +          if: ${{ steps.step1.outputs.send == 'yes' }}
这个目前没有必要保留吧，目前没有场景需要这个输出。而且就算是保留也不能叫这个名字吧

2024-08-21 02:55 UTC, Rosyrain commented on .github/workflows/robot.yaml
> +            REPOSITORY: ${{ github.repository }}  # 获取执行该作业的仓库名 形如: matrixorigin/CI
已改

2024-08-21 03:01 UTC, Rosyrain commented on .github/workflows/robot.yaml
> +            BASE_URL: https://api.github.com
已改

2024-08-21 03:02 UTC, Rosyrain commented on .github/workflows/robot.yaml
> +          if: ${{ steps.step1.outputs.send == 'yes' }}
已改

2024-08-21 03:02 UTC, Rosyrain commented on actions/rm-labels/main.go
> +	labelURL := fmt.Sprintf("%s/repos/%s/issues/%d/labels", baseURL, repo, issueNumber)
已改

2024-08-21 03:02 UTC, Rosyrain commented on actions/rm-labels/pkg/http/http.go
> +func Request(method, url, token string, data io.Reader, contentType string) (resp *http.Response, err error) {
已改

2024-08-21 03:03 UTC, Rosyrain commented on .github/workflows/robot.yaml
> +      if: ${{ github.event_name == 'issues' && github.event.action == 'assigned' && github.event.assignee.login!= 'matrix-meow' }}
放代码里面的话，会不会这个action复用性太低了

2024-08-21 03:10 UTC, Rosyrain commented
新测试action：https://github.com/Rosyrain/github_action_test/actions/runs/10482790577/job/29034514244
测试issue: https://github.com/Rosyrain/github_action_test/issues/53
存在问题：当要删除的标签不存在时，状态码返回404，我会抛出一个err进行panic处理。这个404需要单独处理么

2024-08-21 03:11 UTC, guguducken commented on .github/workflows/robot.yaml
> +      if: ${{ github.event_name == 'issues' && github.event.action == 'assigned' && github.event.assignee.login!= 'matrix-meow' }}
我觉得放到代码中使用逻辑才会更清晰吧。如果只是删除一个label的话，没必要复用这个action，直接在需要删除label的地方调用一下api就好了

2024-08-21 03:12 UTC, guguducken commented on .github/workflows/robot.yaml
> +            BASE_URL: https://api.github.com
没有变化

2024-08-21 03:12 UTC, guguducken commented on .github/workflows/robot.yaml
> +            REPOSITORY: ${{ github.repository }}  # 获取执行该作业的仓库名 形如: matrixorigin/CI
没有变化

2024-08-21 03:12 UTC, guguducken commented on .github/workflows/robot.yaml
> +          if: ${{ steps.step1.outputs.send == 'yes' }}
没有变化

2024-08-22 09:01 UTC, Rosyrain commented
测试action：https://github.com/Rosyrain/github_action_test/actions/runs/10504980325/job/29101585163
测试issue：https://github.com/Rosyrain/github_action_test/issues/53
测试结果
<img width="985" alt="image" src="https://github.com/user-attachments/assets/e28ecd57-df29-4d9a-9deb-56540a413ac4">

2024-08-26 05:02 UTC, guguducken requested changes

2024-08-26 05:02 UTC, guguducken commented on .github/workflows/robot.yaml
> +          current_assignee: ${{ github.event.assignee.login }}
这里可能会有多个assignee，如果第一个不是matrix-meow。但是在后面的assignees中如果还有matrix-meow的话这里是否还需要移除label吗？

2024-08-26 06:40 UTC, Rosyrain commented on .github/workflows/robot.yaml
> +          current_assignee: ${{ github.event.assignee.login }}
已测试，当一次选择多个assignee，会触发多条对应的action。意味着即便有多个assignees，只要存在黑名单列表外的assignee便会导致needs- triage删除

2024-08-27 03:18 UTC, guguducken approved these changes

2024-08-27 03:18 UTC, merged